### ISSUE TITLE
[BUG] 현재 한 파티에서 유저 1명에 대한 노쇼가 딱 한번밖에 안되는 문제(내용에 상황설명 있습니다)

### ISSUE THREAD

**Issue by jwoon1013** [chanoChoi/party#163]
파티장 (글작성자) : 유저1 
파티원 : 유저2, 유저3

상황에서,
유저1 이 유저2를 노쇼신고 하면
유저3 이 유저2를 노쇼 신고 할 수 없는 상황.

**Comment by hobakk** [comment]
문제 해결 완료
