### ISSUE TITLE
모집글 스케쥴러

### ISSUE THREAD

**Issue by jwoon1013** [chanoChoi/party#54]
모집마감 시간이 되면 모집글 자동 마감 기능 구현
모집글 : FINDING (모집중) - FOUND(모집마감) - NO_SHOW_REPORTING(노쇼카운트가능시간), END(종료)
FOUND : FINDING 상태중 모집마감 시간이 됐는데, 모집인원과 ACCEPT 된 APPLICATION의 수가 일치할 때
NO_SHOW_REPORTING : FOUND 상태중 모임시작시간이 됐을 때
END : (1) 모집마감시간이 됐는데, 모집인원과 APPLICATIONS 수가 일치하지 않을 때 (2) NO_SHOW_REPORTING 상태중 모임시간으로부터 1시간 지났을 때

- [x] 1분마다 작동하는 스프링 스케쥴러 구현
- [x] 로직1 : FINDING > FOUND 
- [x] 로직2 : FOUND > NO_SHOW_REPORTING
- [x] 로직3 : FINDING > END
- [x] 로직4 : NO_SHOW_REPORTING > END

**Comment by jwoon1013** [comment]
FINDING -> END (모집마감시간이 됐는데, 다 안모였을 때) 구현방식 고민중

방법 1) application 레퍼지토리에서 count 쿼리를 날려서 해당 postid를 갖고있으면서 ACCEPT된 application이 몇개인가 세서 그것이 partyPost의 maxMember 수와 일치하는경우 FOUND 로 바꾸고, 아닌경우 END로 바꾼다. 
>> 모집마감시간이 된 모든 PARTYPOST의 POSTID를 갖고있는 APPLICATION을 일일이 다 세야하니 어마어마하게 부하가 갈 것 같음

방법 2) 그냥 PARTYPOST에게 int acceptedMember 값을 주고 application이 ACCEPT 될 때마다 이 값을 올려서 모집마감시간에 
acceptedMember+1 = maxmember 인지 확인하고 아닐경우 END 로 보내는게 깔끔하지 않나 생각중입니다.

방법2 가 나을것 같은데 혹시 이 외의 방법이 있을까요? 
@chanoChoi

**Comment by chanoChoi** [comment]
게시물마감시간 전에 주최자가 신청을 수락하면 인원이 증가를 할테니 마감전에 인원이 모집이 완료되었다면 이미 found 상태가 되어있을겁니다.
그러니 마감시간인데 현재 finding이다 그러면 그냥 end로 봐꿔주면 된다고 생각합니다.

**Comment by jwoon1013** [comment]
감샤합니다 accept 할 때 꽉 차있으면 FOUND 로 바꾸는거로 알고, 마감시간 됐는데 FINDING 상태인경우 END로 바뀌게 수정했습니다. 완료~
