### ISSUE TITLE
postman 테스트 & 오류 수정

### ISSUE THREAD

**Issue by jwoon1013** [chanoChoi/party#65]
postman 기반 테스트, 오류 수정중 자세한 수정사항은 커밋메세지 참고해주세요

**Comment by jwoon1013** [comment]
@hobakk 회원가입시 닉네임이랑 이메일 검증 로직 방식을 조금 바꾸는게 어떨까 제안 해두었습니다! 
바로 위의 커밋 내용 한번 확인 해주세여!

**Comment by hobakk** [comment]
exits 확인했습니다 좋네요 bb 다른곳에도 응용해야 겠습니다
